# Generated by Django 4.2.7 on 2023-12-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservationconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='closeDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationrequest',
            name='openDate',
            field=models.DateField(),
        ),
    ]
