# Generated by Django 4.2.7 on 2023-12-02 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reservationrequest_closedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationconfirmed',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationconfirmed',
            name='date',
            field=models.DateField(),
        ),
    ]
